---
version: 1
formatters: 
  default: 
    format: '%(asctime)s | %(name)-24s - %(levelname)-8s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  client:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: pyCubeSat.log
    when: W6
    backupCount: 3
    encoding: UTF-8
    level: DEBUG
  client_console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
    stream: ext://sys.stdout
loggers:
  pyCubeSat:
    handlers: [client, client_console]
    level: DEBUG
    propogate: false
  pyCubeSat.Orbit:
    level: DEBUG
    propogate: true
  pyCubeSat.PMACS:
    level: DEBUG
    propoagte: true
    pyCubeSat.PMACS.Dyanmics:
    level: DEBUG
    propoagte: true
  pyCubeSat.PMACS.IGRF:
    level: DEBUG
    propogate: true